6-2-led_and_button:
	cargo hf2 --example 6-2-led_and_button

6-2-led_and_button_driver:
	cargo hf2 --example 6-2-led_and_button_driver

6-3-uart:
	cargo hf2 --example 6-3-uart

6-3-echo:
	cargo hf2 --example 6-3-echo
